In [1]:
import pandas as pd

In [22]:
d={'names':['rohan','sandesh','shreeharsha','theju','tushar','varun'],'usn':[80,88,102,117,118,124]}
df=pd.DataFrame(d,index=[f'4GM20CS{x}' for x in d["usn"]])
df

                  names  usn
4GM20CS80         rohan   80
4GM20CS88       sandesh   88
4GM20CS102  shreeharsha  102
4GM20CS117        theju  117
4GM20CS118       tushar  118
4GM20CS124        varun  124

In [27]:
s=pd.Series(['rohan','sandesh','shreeharsha','theju','tushar','varun'],name='TEAM',index=[80,88,102,117,118,124])
s

80           rohan
88         sandesh
102    shreeharsha
117          theju
118         tushar
124          varun
Name: TEAM, dtype: object

In [31]:
car_data=pd.read_csv(r"C:\Users\varun\PycharmProjects\ssc_presentation\car_data.csv")
car_data

,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,price_binned
0,3,41,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,13495,low
1,3,41,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500,low
2,1,41,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500,low
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950,low
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,10.217391,28,16845,low
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160,5300,12.368421,25,19045,mid
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134,5500,13.055556,23,21485,mid
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,idi,3.01,3.40,23.0,106,4800,9.038462,27,22470,mid
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,12.368421,25,22625,mid

In [35]:
car_data.loc[0:100,].to_csv('car_data2.csv')