In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\varun\PycharmProjects\ssc_presentation\car_data2.csv')

In [3]:
df.columns

Index(['Unnamed: 0', 'symboling', 'normalized_losses', 'make', 'fuel_type',
       'aspiration', 'num_of_doors', 'body_style', 'drive_wheels',
       'engine_location', 'wheel_base', 'length', 'width', 'height',
       'curb_weight', 'engine_type', 'num-of_cylinders', 'engine_size',
       'fuel_system', 'bore', 'stroke', 'compression_ratio', 'horsepower',
       'peak_rpm', 'city_mpg', 'highway_mpg', 'price', 'price_binned'],
      dtype='object')

In [4]:
df1=df.make.map(lambda x: x.upper())

In [5]:
df.make
df1

0      ALFA-ROMERO
1      ALFA-ROMERO
2      ALFA-ROMERO
3             AUDI
4             AUDI
          ...
96          NISSAN
97          NISSAN
98          NISSAN
99          NISSAN
100         NISSAN
Name: make, Length: 101, dtype: object

In [6]:
df.num_of_doors.value_counts()

two     53
four    48
Name: num_of_doors, dtype: int64

In [7]:
def convert(row):
    d={'two':2,'four':4}
    #n=row.num_of_doors
    row.num_of_doors=d.get(row.num_of_doors)
    return row
df3=df.apply(convert,axis=1)
df3

,Unnamed: 0,symboling,normalized_losses,make,fuel_type,aspiration,num_of_doors,body_style,drive_wheels,engine_location,...,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price,price_binned
0,0,3,41,alfa-romero,gas,std,2,convertible,rwd,front,...,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,13495,low
1,1,3,41,alfa-romero,gas,std,2,convertible,rwd,front,...,mpfi,3.47,2.68,9.0,111,5000,11.190476,27,16500,low
2,2,1,41,alfa-romero,gas,std,2,hatchback,rwd,front,...,mpfi,2.68,3.47,9.0,154,5000,12.368421,26,16500,low
3,3,2,164,audi,gas,std,4,sedan,fwd,front,...,mpfi,3.19,3.40,10.0,102,5500,9.791667,30,13950,low
4,4,2,164,audi,gas,std,4,sedan,4wd,front,...,mpfi,3.19,3.40,8.0,115,5500,13.055556,22,17450,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,96,1,122,nissan,gas,std,4,sedan,fwd,front,...,2bbl,3.15,3.29,9.4,69,5200,7.580645,37,7499,low
97,97,1,103,nissan,gas,std,4,wagon,fwd,front,...,2bbl,3.15,3.29,9.4,69,5200,7.580645,37,7999,low
98,98,2,168,nissan,gas,std,2,hardtop,fwd,front,...,2bbl,3.15,3.29,9.4,69,5200,7.580645,37,8249,low
99,99,0,106,nissan,gas,std,4,hatchback,fwd,front,...,2bbl,3.33,3.47,8.5,97,5200,8.703704,34,8949,low
100,100,0,106,nissan,gas,std,4,sedan,fwd,front,...,2bbl,3.33,3.47,8.5,97,5200,8.703704,34,9549,low

In [8]:
df.describe

<bound method NDFrame.describe of      Unnamed: 0  symboling  normalized_losses         make fuel_type  \
0             0          3                 41  alfa-romero       gas
1             1          3                 41  alfa-romero       gas
2             2          1                 41  alfa-romero       gas
3             3          2                164         audi       gas
4             4          2                164         audi       gas
..          ...        ...                ...          ...       ...
96           96          1                122       nissan       gas
97           97          1                103       nissan       gas
98           98          2                168       nissan       gas
99           99          0                106       nissan       gas
100         100          0                106       nissan       gas

    aspiration num_of_doors   body_style drive_wheels engine_location  ...  \
0          std          two  convertible          rwd           front  ...
1          std          two  convertible          rwd           front  ...
2          std          two    hatchback          rwd           front  ...
3          std         four        sedan          fwd           front  ...
4          std         four        sedan          4wd           front  ...
..         ...          ...          ...          ...             ...  ...
96         std         four        sedan          fwd           front  ...
97         std         four        wagon          fwd           front  ...
98         std          two      hardtop          fwd           front  ...
99         std         four    hatchback          fwd           front  ...
100        std         four        sedan          fwd           front  ...

     fuel_system  bore  stroke  compression_ratio  horsepower peak_rpm  \
0           mpfi  3.47    2.68                9.0         111     5000
1           mpfi  3.47    2.68                9.0         111     5000
2           mpfi  2.68    3.47                9.0         154     5000
3           mpfi  3.19    3.40               10.0         102     5500
4           mpfi  3.19    3.40                8.0         115     5500
..           ...   ...     ...                ...         ...      ...
96          2bbl  3.15    3.29                9.4          69     5200
97          2bbl  3.15    3.29                9.4          69     5200
98          2bbl  3.15    3.29                9.4          69     5200
99          2bbl  3.33    3.47                8.5          97     5200
100         2bbl  3.33    3.47                8.5          97     5200

      city_mpg  highway_mpg  price  price_binned
0    11.190476           27  13495           low
1    11.190476           27  16500           low
2    12.368421           26  16500           low
3     9.791667           30  13950           low
4    13.055556           22  17450           low
..         ...          ...    ...           ...
96    7.580645           37   7499           low
97    7.580645           37   7999           low
98    7.580645           37   8249           low
99    8.703704           34   8949           low
100   8.703704           34   9549           low

[101 rows x 28 columns]>

In [10]:
df.fuel_type.unique()

array(['gas', 'diesel'], dtype=object)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 28 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         101 non-null    int64
 1   symboling          101 non-null    int64
 2   normalized_losses  101 non-null    int64
 3   make               101 non-null    object
 4   fuel_type          101 non-null    object
 5   aspiration         101 non-null    object
 6   num_of_doors       101 non-null    object
 7   body_style         101 non-null    object
 8   drive_wheels       101 non-null    object
 9   engine_location    101 non-null    object
 10  wheel_base         101 non-null    float64
 11  length             101 non-null    float64
 12  width              101 non-null    float64
 13  height             96 non-null     float64
 14  curb_weight        101 non-null    int64
 15  engine_type        101 non-null    object
 16  num-of_cylinders   101 non-null    object
 17  engine_size        101 non-null    int64
 18  fuel_system        101 non-null    object
 19  bore               101 non-null    float64
 20  stroke             101 non-null    float64
 21  compression_ratio  101 non-null    float64
 22  horsepower         101 non-null    int64
 23  peak_rpm           101 non-null    int64
 24  city_mpg           101 non-null    float64
 25  highway_mpg        101 non-null    int64
 26  price              101 non-null    int64
 27  price_binned       101 non-null    object
dtypes: float64(8), int64(9), object(11)
memory usage: 22.2+ KB